FROM python:3.11-slim

WORKDIR /backend

COPY backend/requirements.txt /backend/requirements.txt

RUN apt-get update && \
    apt-get install -y \
        default-libmysqlclient-dev \
        build-essential \
        pkg-config && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /backend/requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY backend /backend

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
